export default {
  formId: null,
  title: "新的问卷1",
  description: "想着就是一个氨基酸返回数据殴打和服从",
  categoryId: null,
  questions: [
    {
      title: "测试区",
      type: "text",
      name: "question1",

      indent: 0,
      titleLocation: "top",
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: "time",
      inputVariant: null,
      precision: -1,
      isRequired: true,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: null,
      columns: null,
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "121232",
      type: "radiogroup",
      name: "question2",
      indent: 0,
      titleLocation: "top",
      showQuestionNumber: true,
      orientation: "vertical",
      choices: [
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      showOtherItem: true,
      otherText: "123",
      otherPlaceholder: "123",
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: null,
      columns: null,
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question3",
      type: "checkbox",
      name: "question3",
      indent: 0,
      titleLocation: "top",
      showQuestionNumber: true,
      orientation: "vertical",
      choices: [
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: null,
      columns: null,
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question4",
      type: "dropdown",
      name: "question4",
      indent: 0,
      titleLocation: "top",
      showQuestionNumber: true,
      orientation: "vertical",
      choices: [
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Item2",
          value: "item2",
          score: null,
          cellType: null,
          multipleChoice: null,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: null,
      columns: null,
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question5",
      type: "file",
      name: "question5",
      indent: 0,
      titleLocation: "top",
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: null,
      columns: null,
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "",
      type: "panel",
      name: "panel6",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: false,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: [],
      gridRows: null,
      rows: null,
      columns: null,
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question6",
      type: "matrixradio",
      name: "question6",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: [
        {
          text: "Row1",
          value: "row1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Row2",
          value: "row2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      columns: [
        {
          text: "Column1",
          value: "column1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Column2",
          value: "column2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question7",
      type: "matrixcheckbox",
      name: "question7",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: true,
      orientation: null,
      choices: [],
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: [
        {
          text: "Row1",
          value: "row1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Row2",
          value: "row2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      columns: [
        {
          text: "Column1",
          value: "column1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Column2",
          value: "column2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question8",
      type: "matrixdropdown",
      name: "question8",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: [
        {
          text: "Row1",
          value: "row1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Row2",
          value: "row2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      columns: [
        {
          text: "Column1",
          value: "column1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Column2",
          value: "column2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question9",
      type: "matrixinput",
      name: "question9",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: null,
      rows: [
        {
          text: "Row1",
          value: "row1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Row2",
          value: "row2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      columns: [
        {
          text: "Column1",
          value: "column1",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Column2",
          value: "column2",
          score: null,
          cellType: null,
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      cells: null,
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question10",
      type: "grid",
      name: "question10",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: ["row1", "row2", "row3"],
      rows: null,
      columns: [
        {
          text: "Column1",
          value: "column1",
          score: null,
          cellType: "text",
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Column2",
          value: "column2",
          score: null,
          cellType: "text",
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      cells: {},
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
    {
      title: "question11",
      type: "grid",
      name: "question11",
      indent: 0,
      titleLocation: null,
      showQuestionNumber: true,
      orientation: null,
      choices: null,
      showOtherItem: false,
      otherText: null,
      otherPlaceholder: null,
      dropdownPlaceholder: null,
      placeholder: null,
      inputType: null,
      inputVariant: null,
      precision: null,
      isRequired: false,
      readOnly: false,
      maxLength: 0,
      maxSize: 0,
      acceptedTypes: null,
      maxNumber: 0,
      innerIndent: 0,
      questions: null,
      gridRows: ["row3"],
      rows: null,
      columns: [
        {
          text: "Column1",
          value: "column1",
          score: null,
          cellType: "dropdown",
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
        {
          text: "Column2",
          value: "column2",
          score: null,
          cellType: "text",
          multipleChoice: false,
          cellText: null,
          inputType: null,
          maxLength: 0,
          placeholder: null,
          precision: null,
          dropdownPlaceholder: null,
          choices: null,
        },
      ],
      cells: {
        row3: {
          column2: {
            text: null,
            value: null,
            score: null,
            cellType: "input",
            multipleChoice: null,
            cellText: null,
            inputType: "text",
            maxLength: 500,
            placeholder: "123",
            precision: null,
            dropdownPlaceholder: null,
            choices: null,
          },
        },
      },
      visibleIf: null,
      editableIf: null,
      requiredIf: null,
      defaultExpression: null,
    },
  ],
};
