export default {
  ethicalApprovalNo: null,
  croTelephone: "固定电话(CRO)",
  isFreeDrug: "item1",
  setupTime: 1723132800000,
  source: "ctms",
  expectedSubjectsNum: 1,
  dataSaveYearsType: "item1",
  bidPartyCroAdress: "北京市丰台区丰台北路 18号院3号楼21层 2101内2103",
  projectNo: "fdfdsf",
  bidPartyCro: "无锡福欣医药研宄开发有限公司",
  bidPartyCroTelephone: "15035692535",
  dataHandlePersonType: "item1",
  institutionalOfficeSignDate: 1723132800000,
  state: "NOT_APPROVED",
  id: "0",
  submitDataList:
    "国家药品监督管理局药物临床试验批件/临床试验通知书 （有效）\n药检报告（备案药检报告智无法出具说明）\n申办者资质/CRO 资质证明（有效，GMP 证书、营业执照、生产许可证等)\n研究者手册（版本号：V1.2，版本日期：2023.01.06）\n试验方案（版本号 v2.1.版本日期 2023.06.21， PI、申办方及 CRO 签字）\n招葬广告（版本号：长治医学院附属和平医院专用版 V1.0版本日期：2023.07.20)\n知情同意书 （版本号：长治医学院附属和平医院专用版 V1.0 版本日期：2023.07.20)\n国家药品监督管理局药物临床试验批件/临床试验通知书 （有效）\n国家药品监督管理局药物临床试验批件/临床试验通知书 （有效）",
  batchNo: "2018103084\n2018L03083\n2018L03082",
  expertSignDate: 1723737600000,
  bookmarkDeliverAreaType: "item1",
  isFreeCheck: "item1",
  dataHandleOrg: "ff",
  testCategory: "1",
  bidPartyCroContact: "联系人",
  mainResearcherAccount: "pi",
  expersStatus: {
    blank2: "2",
    blank3: "3",
    blank1: "1",
    blank5: "4",
  },
  drugName: "WYFL10203614 H",
  projectName:
    "评价 WXFL10203614 片治疗中重度活动性类风湿关节炎(RA)有效性和安仝性的清机、双盲双模拟、多中心、阳性药及安慰剂对照的山 期临床研究",
  deptCode: "院领导,办公室",
  status: "item1",
  croAdress: "通信地址(CRO)",
  question4: "item2",
  headed: "中国医学科学院北京协和医院",
  cfdaProApprovalNo: "",
  agreeOptions: "item1",
  croContact: "联系人(CRO)",
  officeAdvice:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure sed dolorem rerum odio illum nobis molestias laboriosam. Quisquam aliquid quasi assumenda, sint ex quae debitis voluptate totam quis aperiam cupiditate.Maxime molestias eos modi ratione est voluptates, fuga ut corrupti magni enim molestiae omnis dolor tenetur, accusantium repellat praesentium? Autem quod aliquam consequatur qui, mollitia blanditiis. Dolorum provident illum numquam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure sed dolorem rerum odio illum nobis molestias laboriosam. Quisquam aliquid quasi assumenda, sint ex quae debitis voluptate totam quis aperiam cupiditate.Maxime molestias eos modi ratione est voluptates, fuga ut corrupti magni enim molestiae omnis dolor tenetur, accusantium repellat praesentium? Autem quod aliquam consequatur qui, mollitia blanditiis. Dolorum provident illum numquam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure sed dolorem rerum odio illum nobis molestias laboriosam. Quisquam aliquid quasi assumenda, sint ex quae debitis voluptate totam quis aperiam cupiditate.Maxime molestias eos modi ratione est voluptates, fuga ut corrupti magni enim molestiae omnis dolor tenetur, accusantium repellat praesentium? Autem quod aliquam consequatur qui, mollitia blanditiis. Dolorum provident illum numquam.",
  formToken: "9e36c749-0259-4cfb-b208-2633f8f8b257",
  croName: "CRO名称",
  freeDrugStyle: "item1",
  startTime: 1723132800000,
  officeSignDate: 1723478400000,
  examineeSubsidyType: "item1",
  isBookmarkDeliver: "item1",
  bookmarkDeliverType: "item1",
  isExamineeSubsidy: "item1",
  ethicalFilePath: "a48f1082-d70a-454c-b733-c364c27eff4c",
  stage: "item5",
  expectedEndTime: null,
  category: "化学药品第-类",
  planStartEndTime: [1727107200000, 1727366400000],
  PISignDate: 1724774400000,
  isInternationalMultiCentering: "item1",
  stateProcess: "NOT_COMPLETE",
};
